
FROM node:12 AS builder

# set working directory
WORKDIR /app

# install and cache app dependencies
COPY *.json *.js ./

RUN npm install --silent && npm cache clean -f

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# add app
COPY . /app

EXPOSE 4200

# start app
CMD ["npm", "run", "start"]
